Repository mib1185/py-synologydsm-api, pull requests merged in 2023-01, with the labels that each got.

#222 Remove poetry and nox as build dependencies
  .devcontainer/Dockerfile
  .github/workflows/constraints.txt
  .github/workflows/tests.yml
  .vscode/tasks.json
  poetry.lock
  poetry.toml
  pyproject.toml
  requirements.txt
  requirements_dev.txt
  scripts/setup
  setup.cfg
Labels: dependencies, build

#221 BREAKING: Rework to aiohttp
  .vscode/tasks.json
  README.rst
  pyproject.toml
  requirements_dev.txt
  src/synology_dsm/api/core/security.py
  src/synology_dsm/api/core/share.py
  src/synology_dsm/api/core/system.py
  src/synology_dsm/api/core/upgrade.py
  src/synology_dsm/api/core/utilization.py
  src/synology_dsm/api/download_station/__init__.py
  src/synology_dsm/api/dsm/information.py
  src/synology_dsm/api/dsm/network.py
  src/synology_dsm/api/storage/storage.py
  src/synology_dsm/api/surveillance_station/__init__.py
  src/synology_dsm/synology_dsm.py
  tests/__init__.py
  tests/conftest.py
  tests/test_synology_dsm.py
  tests/test_synology_dsm_5.py
  tests/test_synology_dsm_6.py
  tests/test_synology_dsm_7.py
Labels: breaking, refactoring

#227 Add python 3.10
  .github/workflows/release.yml
  .github/workflows/tests.yml
  pyproject.toml
Labels: dependencies

#232 Fix double url encoding for GET requests
  src/synology_dsm/synology_dsm.py
Labels: bugfix

#233 Fix cameras not reading data as bytes
  src/synology_dsm/api/__init__.py
  src/synology_dsm/synology_dsm.py
Labels: bugfix

#235 Fix exception in case of request error
  src/synology_dsm/synology_dsm.py
Labels: bugfix

#236 Remove requirements.txt and update Visual Studio Code Dev Container
  .github/workflows/tests.yml
  .vscode/tasks.json
  CONTRIBUTING.rst
  requirements.txt
  requirements_dev.txt
  scripts/setup
  tests/__init__.py
  tests/test_synology_dsm.py
Labels: build

#170 Added synology photos api
  README.rst
  src/synology_dsm/api/photos/__init__.py
  src/synology_dsm/api/photos/model.py
  src/synology_dsm/synology_dsm.py
  tests/__init__.py
  tests/api_data/dsm_7/__init__.py
  tests/api_data/dsm_7/const_7_api_info.py
  tests/api_data/dsm_7/photos/__init__.py
  tests/api_data/dsm_7/photos/const_7_photo.py
  tests/test_synology_dsm.py
  tests/test_synology_dsm_7.py
Labels: enhancement

#240 Drop python 3.7 support
  .devcontainer/Dockerfile
  .github/workflows/tests.yml
  .pre-commit-config.yaml
  pyproject.toml
Labels: breaking

#239 Improve Dev-Container
  .devcontainer/devcontainer.json
  .vscode/settings.default.json
  CONTRIBUTING.md
  CONTRIBUTING.rst
  README.md
  README.rst
  pyproject.toml
Labels: build

#241 login() must be done consciously
  src/synology_dsm/exceptions.py
  src/synology_dsm/synology_dsm.py
  tests/test_synology_dsm.py
  tests/test_synology_dsm_5.py
  tests/test_synology_dsm_6.py
  tests/test_synology_dsm_7.py
Labels: breaking
