Repository mib1185/py-synologydsm-api, pull requests merged in 2023-02, with the labels that each got.

#252 Fetch asyncio timeout error
  src/synology_dsm/synology_dsm.py
Labels: bugfix

#253 Fix SynologyDSMRequestException
  src/synology_dsm/exceptions.py
Labels: bugfix

#254 Fix kwargs handling in requests
  src/synology_dsm/synology_dsm.py
Labels: bugfix

#260 Fix handling user names and passwords with spaces
  src/synology_dsm/synology_dsm.py
Labels: bugfix

#261 Improved handling of special characters in parameters
  src/synology_dsm/synology_dsm.py
Labels: bugfix

#183 Introduce type annotations
  .devcontainer/devcontainer.json
  .github/workflows/tests.yml
  .pre-commit-config.yaml
  .vscode/settings.default.json
  mypy.ini
  pyproject.toml
  requirements_dev.txt
  src/synology_dsm/api/__init__.py
  src/synology_dsm/api/core/security.py
  src/synology_dsm/api/core/share.py
  src/synology_dsm/api/core/system.py
  src/synology_dsm/api/core/upgrade.py
  src/synology_dsm/api/core/utilization.py
  src/synology_dsm/api/download_station/__init__.py
  src/synology_dsm/api/download_station/task.py
  src/synology_dsm/api/dsm/information.py
  src/synology_dsm/api/dsm/network.py
  src/synology_dsm/api/photos/__init__.py
  src/synology_dsm/api/storage/storage.py
  src/synology_dsm/api/surveillance_station/__init__.py
  src/synology_dsm/api/surveillance_station/camera.py
  src/synology_dsm/const.py
  src/synology_dsm/exceptions.py
  src/synology_dsm/helpers.py
  src/synology_dsm/py.typed
  src/synology_dsm/synology_dsm.py
Labels: build, code_quality

#251 Add external USB storage devices
  README.md
  src/synology_dsm/api/core/external_usb.py
  src/synology_dsm/synology_dsm.py
  tests/__init__.py
  tests/api_data/dsm_7/__init__.py
  tests/api_data/dsm_7/core/const_7_core_external_usb.py
  tests/test_synology_dsm.py
  tests/test_synology_dsm_7.py
Labels: enhancement
